<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" 
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
                xmlns:news="http://www.google.com/schemas/sitemap-news/0.9"
                xmlns:xhtml="http://www.w3.org/1999/xhtml"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<html xmlns="http://www.w3.org/1999/xhtml">
			<head>
				<title>XML Sitemap - ArabPsychology Academic Portal</title>
				<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
				<style type="text/css">
					body {
						font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
						color: #333;
						margin: 0;
						padding: 40px;
						background: #f4f7f9;
					}
					#content {
						max-width: 1000px;
						margin: 0 auto;
						background: #fff;
						padding: 40px;
						border-radius: 12px;
						box-shadow: 0 10px 30px rgba(0,0,0,0.05);
					}
					h1 { color: #1a1a1a; margin-top: 0; font-size: 28px; }
					p { color: #666; line-height: 1.6; }
					table { width: 100%; border-collapse: collapse; margin-top: 30px; }
					th { text-align: left; padding: 12px; border-bottom: 2px solid #eee; color: #1a1a1a; font-weight: 600; }
					td { padding: 12px; border-bottom: 1px solid #eee; font-size: 14px; }
					tr:hover td { background: #fcfcfc; }
					a { color: #2271b1; text-decoration: none; }
					a:hover { text-decoration: underline; }
					.count { color: #888; font-size: 12px; float: right; margin-top: 10px; }
					.footer { margin-top: 40px; font-size: 12px; color: #999; text-align: center; }
				</style>
			</head>
			<body>
				<div id="content">
					<h1>Academic Platform Sitemap</h1>
					<p>This is a specialized XML Sitemap generated for the ArabPsychology Research and LMS platform. It contains all indexed academic news, glossary terms, and courses.</p>
					
					<xsl:choose>
						<xsl:when test="//*[local-name()='sitemapindex']">
							<p>This is a sitemap index file. Click on individual sitemaps below to see their content.</p>
							<table>
								<thead>
									<tr>
										<th>Sitemap URL</th>
										<th>Last Modified</th>
									</tr>
								</thead>
								<tbody>
									<xsl:for-each select="//*[local-name()='sitemap']">
										<tr>
											<td>
												<xsl:variable name="itemURL" select="*[local-name()='loc']"/>
												<a href="{$itemURL}"><xsl:value-of select="*[local-name()='loc']"/></a>
											</td>
											<td><xsl:value-of select="*[local-name()='lastmod']"/></td>
										</tr>
									</xsl:for-each>
								</tbody>
							</table>
						</xsl:when>
						<xsl:when test="//*[local-name()='urlset']">
							<p class="count">URLs in this sitemap: <xsl:value-of select="count(//*[local-name()='url'])"/></p>
							<table>
								<thead>
									<tr>
										<th>URL</th>
										<th>Images</th>
										<th>Last Mod</th>
									</tr>
								</thead>
								<tbody>
									<xsl:for-each select="//*[local-name()='url']">
										<tr>
											<td>
												<xsl:variable name="itemURL" select="*[local-name()='loc']"/>
												<a href="{$itemURL}"><xsl:value-of select="*[local-name()='loc']"/></a>
											</td>
											<td>
												<xsl:value-of select="count(*[local-name()='image'])"/>
											</td>
											<td><xsl:value-of select="*[local-name()='lastmod']"/></td>
										</tr>
									</xsl:for-each>
								</tbody>
							</table>
						</xsl:when>
					</xsl:choose>

					<div class="footer">
						Generated by WP Academic Post Enhanced — Designed for Research.
					</div>
				</div>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
